# Generated by Django 4.2.7 on 2025-05-25 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=20, unique=True, verbose_name='Form Number (CA/F/PSM/17)')),
                ('inspection_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('technical_personnel', models.CharField(blank=True, max_length=200, verbose_name='Name of Technical Personnel responsible for Maintenance')),
                ('other_observations', models.TextField(blank=True, verbose_name='Any Other Observations')),
                ('inspector_signature_date', models.DateField(blank=True, null=True)),
                ('contact_signature_date', models.DateField(blank=True, null=True)),
                ('last_saved', models.DateTimeField(auto_now=True)),
                ('is_auto_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('broadcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='broadcasters.broadcaster')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspections',
                'ordering': ['-created_at'],
            },
        ),
    ]
