# Generated by Django 4.2.7 on 2025-05-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_above_building_roof_inspection_altitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='station_type',
            field=models.CharField(blank=True, choices=[('DAB', 'DAB (Digital Audio Broadcasting)'), ('FM', 'FM (Frequency Modulation)'), ('DTT', 'DTT (Digital Terrestrial Television) / DVB-T')], max_length=10, null=True),
        ),
    ]
