# Generated by Django 4.2.7 on 2025-05-30 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasters', '0003_generaldata_air_status_generaldata_off_air_reason_and_more'),
        ('inspections', '0003_update_station_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='air_status',
            field=models.CharField(choices=[('on_air', 'ON AIR'), ('off_air', 'OFF AIR')], default='on_air', max_length=10, verbose_name='Air Status'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='off_air_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for being OFF AIR (if applicable)'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='broadcasters.programname', verbose_name='Program Reference'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='program_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Program Name'),
        ),
    ]
