# Generated by Django 4.2.7 on 2025-05-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasters', '0003_generaldata_air_status_generaldata_off_air_reason_and_more'),
        ('inspections', '0004_inspection_air_status_inspection_off_air_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='estimated_system_losses',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='stl_type',
            field=models.CharField(blank=True, choices=[('ip_based', 'IP-Based STL (Internet Protocol)'), ('satellite', 'Satellite STL'), ('vhf', 'VHF STL'), ('studio_on_site', 'Studio On Site (SOS)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='broadcaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='broadcasters.broadcaster'),
        ),
    ]
