# Generated by Django 4.2.7 on 2025-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_inspection_estimated_system_losses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='effective_radiated_power_dbw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Effective Radiated Power (dBW)'),
        ),
    ]
