# Generated by Django 5.2.1 on 2025-06-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_inspection_effective_radiated_power_dbw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='filter_type',
            field=models.CharField(blank=True, choices=[('standard_band_pass', 'Standard Band Pass Filter'), ('notch', 'Notch Filter'), ('high_q_triple_cavity', 'High-Q Triple Cavity Filter')], max_length=50, null=True),
        ),
    ]
