# Generated by Django 4.2.7 on 2025-05-25 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of Broadcaster')),
                ('po_box', models.CharField(blank=True, max_length=50, verbose_name='P.O. Box')),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('phone_numbers', models.TextField(blank=True, verbose_name='Phone Number(s)')),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_address', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Contact Tel No')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'broadcasters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_type', models.CharField(choices=[('AM', 'AM Radio'), ('FM', 'FM Radio'), ('TV', 'Television')], max_length=10, verbose_name='Type of Station')),
                ('transmitting_site_name', models.CharField(max_length=200, verbose_name='Name of the Transmitting Site')),
                ('longitude', models.CharField(blank=True, max_length=20, verbose_name='Longitude (dd mm ss) E')),
                ('latitude', models.CharField(blank=True, max_length=20, verbose_name='Latitude (dd mm ss) N/S')),
                ('physical_location', models.CharField(blank=True, max_length=200)),
                ('physical_street', models.CharField(blank=True, max_length=200)),
                ('physical_area', models.CharField(blank=True, max_length=100)),
                ('altitude', models.CharField(blank=True, max_length=50, verbose_name='Altitude (m above sea level)')),
                ('land_owner_name', models.CharField(blank=True, max_length=200, verbose_name='Name of the Land Owner')),
                ('other_telecoms_operator', models.BooleanField(default=False, verbose_name='Others Telecoms Operator on site?')),
                ('telecoms_operator_details', models.TextField(blank=True, verbose_name='If yes, elaborate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_data', to='broadcasters.broadcaster')),
            ],
            options={
                'db_table': 'general_data',
            },
        ),
    ]
