# Generated by Django 4.2.7 on 2025-05-30 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasters', '0002_programname'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldata',
            name='air_status',
            field=models.CharField(choices=[('on_air', 'ON AIR'), ('off_air', 'OFF AIR')], default='on_air', max_length=10, verbose_name='Air Status'),
        ),
        migrations.AddField(
            model_name='generaldata',
            name='off_air_reason',
            field=models.TextField(blank=True, verbose_name='Reason for being OFF AIR (if applicable)'),
        ),
        migrations.AddField(
            model_name='generaldata',
            name='program_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_data', to='broadcasters.programname', verbose_name='Program Name'),
        ),
    ]
