# Generated by Django 4.2.7 on 2025-05-25 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broadcasters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntennaSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_on_tower', models.CharField(max_length=50, verbose_name='Height the Antenna on the Tower/Mast (m)')),
                ('antenna_type', models.CharField(max_length=100, verbose_name='Type of Antenna')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Antenna Manufacturer')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Antenna Model Number')),
                ('polarization', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('circular', 'Circular'), ('elliptical', 'Elliptical')], max_length=20)),
                ('horizontal_pattern', models.CharField(choices=[('omni_directional', 'Omni directional'), ('directional', 'Directional')], max_length=20)),
                ('beam_width_3db', models.CharField(blank=True, max_length=50, verbose_name='Beam width measured at - 3 dB Level')),
                ('max_gain_azimuth', models.CharField(blank=True, max_length=50, verbose_name='Degrees azimuth for the max gain related to N')),
                ('horizontal_pattern_table', models.TextField(blank=True, verbose_name='Table of azimuth (DbK) value of the Horizontal Pattern (Attach)')),
                ('has_mechanical_tilt', models.BooleanField(default=False, verbose_name='Mechanical tilt?')),
                ('has_electrical_tilt', models.BooleanField(default=False, verbose_name='Electrical tilt?')),
                ('has_null_fill', models.BooleanField(default=False, verbose_name='Null fill?')),
                ('mechanical_tilt_degree', models.CharField(blank=True, max_length=50, verbose_name='Degree of Tilt')),
                ('electrical_tilt_degree', models.CharField(blank=True, max_length=50, verbose_name='Degree of Tilt')),
                ('null_fill_percentage', models.CharField(blank=True, max_length=50, verbose_name='% of filling')),
                ('vertical_pattern_table', models.TextField(blank=True, verbose_name='Table of azimuth (DbK) value of the Vertical Pattern (Attach)')),
                ('antenna_gain', models.CharField(blank=True, max_length=50, verbose_name='Gain of the Antenna System')),
                ('estimated_antenna_losses', models.CharField(blank=True, max_length=50, verbose_name='Estimated antenna losses (splitter, harnesses, null fill losses, etc ) (dB)')),
                ('estimated_feeder_losses', models.CharField(blank=True, max_length=50, verbose_name='Estimated losses in the feeder (dB)')),
                ('estimated_multiplexer_losses', models.CharField(blank=True, max_length=50, verbose_name='Estimated losses in multiplexer (dB)')),
                ('effective_radiated_power', models.CharField(blank=True, max_length=50, verbose_name='Effective Radiated Power (kW)')),
                ('antenna_catalog_attached', models.BooleanField(default=False, verbose_name='Antenna Catalog (attach)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenna_systems', to='broadcasters.generaldata')),
            ],
            options={
                'db_table': 'antenna_systems',
            },
        ),
    ]
