# Generated by Django 4.2.7 on 2025-05-27 08:39

import apps.reports.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0002_inspection_above_building_roof_inspection_altitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('fm_radio', 'FM Radio Inspection'), ('tv_broadcast', 'TV Broadcast Inspection'), ('am_radio', 'AM Radio Inspection')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('title', models.CharField(help_text='Report title (auto-generated from template)', max_length=500)),
                ('reference_number', models.CharField(help_text='CA reference number', max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('findings', models.TextField(blank=True, help_text='Inspection findings')),
                ('observations', models.TextField(blank=True, help_text='Inspector observations')),
                ('conclusions', models.TextField(blank=True, help_text='Report conclusions')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations')),
                ('erp_calculations', models.JSONField(default=dict, help_text='ERP calculations for each channel')),
                ('violations_found', models.JSONField(default=list, help_text='List of violations found')),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('minor_violations', 'Minor Violations'), ('major_violations', 'Major Violations'), ('non_compliant', 'Non-Compliant')], default='compliant', max_length=20)),
                ('preferred_format', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('both', 'Both PDF and Word')], default='pdf', max_length=10)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='reports/generated/')),
                ('generated_docx', models.FileField(blank=True, null=True, upload_to='reports/generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='inspections.inspection')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspection_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('fm_radio', 'FM Radio Inspection'), ('tv_broadcast', 'TV Broadcast Inspection'), ('am_radio', 'AM Radio Inspection')], max_length=20)),
                ('template_structure', models.JSONField(help_text='JSON structure defining the report layout')),
                ('header_template', models.TextField(help_text='Header section template')),
                ('findings_template', models.TextField(help_text='Findings section template')),
                ('calculations_template', models.TextField(help_text='ERP calculations template')),
                ('conclusions_template', models.TextField(help_text='Conclusions template')),
                ('recommendations_template', models.TextField(help_text='Recommendations template')),
                ('page_margins', models.JSONField(default=dict, help_text='Page margin settings')),
                ('font_settings', models.JSONField(default=dict, help_text='Font and styling settings')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_templates',
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.reports.models.report_image_upload_path)),
                ('image_type', models.CharField(choices=[('site_overview', 'Site Overview'), ('tower_structure', 'Tower Structure'), ('exciter', 'Exciter Equipment'), ('amplifier', 'Amplifier Equipment'), ('antenna_system', 'Antenna System'), ('filter', 'Filter Equipment'), ('studio_link', 'Studio Link Equipment'), ('transmitter_room', 'Transmitter Room'), ('equipment_rack', 'Equipment Rack'), ('other', 'Other')], max_length=20)),
                ('caption', models.CharField(help_text='Image caption for the report', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('position_in_report', models.CharField(choices=[('header', 'Header Area'), ('findings_section', 'Findings Section'), ('equipment_section', 'Equipment Section'), ('antenna_section', 'Antenna Section'), ('custom', 'Custom Position')], default='equipment_section', max_length=20)),
                ('order_in_section', models.PositiveIntegerField(default=1, help_text='Order within the section')),
                ('width_percentage', models.PositiveIntegerField(default=80, help_text='Width as percentage of page width')),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('equipment_manufacturer', models.CharField(blank=True, max_length=200)),
                ('equipment_model', models.CharField(blank=True, max_length=200)),
                ('equipment_serial', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.inspectionreport')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_images',
                'ordering': ['position_in_report', 'order_in_section'],
            },
        ),
        migrations.CreateModel(
            name='ERPCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_number', models.CharField(help_text='e.g., CH.22, CH.37', max_length=10)),
                ('frequency_mhz', models.CharField(help_text='Frequency in MHz', max_length=20)),
                ('forward_power_w', models.DecimalField(decimal_places=2, help_text='Forward Power in Watts', max_digits=10)),
                ('antenna_gain_dbd', models.DecimalField(decimal_places=2, help_text='Antenna Gain in dBd', max_digits=5)),
                ('losses_db', models.DecimalField(decimal_places=2, default=1.5, help_text='System Losses in dB', max_digits=5)),
                ('erp_dbw', models.DecimalField(decimal_places=2, help_text='ERP in dBW', max_digits=8)),
                ('erp_kw', models.DecimalField(decimal_places=3, help_text='ERP in kW', max_digits=8)),
                ('authorized_erp_dbw', models.DecimalField(decimal_places=2, default=40.0, help_text='Authorized ERP in dBW', max_digits=8)),
                ('authorized_erp_kw', models.DecimalField(decimal_places=3, default=10.0, help_text='Authorized ERP in kW', max_digits=8)),
                ('is_compliant', models.BooleanField(default=True)),
                ('excess_power_kw', models.DecimalField(blank=True, decimal_places=3, help_text='Excess power if non-compliant', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_details', to='reports.inspectionreport')),
            ],
            options={
                'db_table': 'erp_calculations',
                'ordering': ['channel_number'],
            },
        ),
    ]
