# Generated by Django 5.2.1 on 2025-06-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmitters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='filter_type',
            field=models.CharField(choices=[('standard_band_pass', 'Standard Band Pass Filter'), ('notch', 'Notch Filter'), ('high_q_triple_cavity', 'High-Q Triple Cavity Filter')], max_length=30, verbose_name='Type'),
        ),
    ]
