# Generated by Django 4.2.7 on 2025-05-25 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broadcasters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_owner_name', models.CharField(max_length=200, verbose_name='Name of the Tower Owner')),
                ('height_above_ground', models.CharField(max_length=50, verbose_name='Height of the Tower above Ground')),
                ('above_building_roof', models.BooleanField(default=False, verbose_name='Is the tower above a Building Roof?')),
                ('building_height', models.CharField(blank=True, max_length=50, verbose_name='Height of the building above ground')),
                ('tower_type', models.CharField(choices=[('guyed', 'Guyed'), ('self_supporting', 'Self-Supporting'), ('other', 'Others (specify)')], max_length=20, verbose_name='Type of Tower')),
                ('tower_type_other', models.CharField(blank=True, max_length=100, verbose_name='Others (specify)')),
                ('rust_protection', models.CharField(choices=[('galvanized', 'Galvanized'), ('painted', 'Painted'), ('aluminum', 'Aluminum'), ('no_protection', 'No Rust Protection')], max_length=20, verbose_name='Rust Protection')),
                ('installation_year', models.CharField(blank=True, max_length=4, verbose_name='Year of Tower installation')),
                ('manufacturer_name', models.CharField(blank=True, max_length=200, verbose_name='Name of the Tower Manufacturer')),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('maximum_wind_load', models.CharField(blank=True, max_length=50, verbose_name='Maximum Wind Load (km/h)')),
                ('maximum_load_charge', models.CharField(blank=True, max_length=50, verbose_name='Maximum Load Charge (kg)')),
                ('has_insurance', models.BooleanField(default=False, verbose_name='Has Tower got an Insurance Policy?')),
                ('insurance_company', models.CharField(blank=True, max_length=200, verbose_name='Name of insurer')),
                ('has_concrete_base', models.BooleanField(default=False, verbose_name='Concrete Base?')),
                ('has_lightning_protection', models.BooleanField(default=False, verbose_name='Lightning Protection provided?')),
                ('is_electrically_grounded', models.BooleanField(default=False, verbose_name='Is the Tower electrically grounded?')),
                ('has_aviation_warning_light', models.BooleanField(default=False, verbose_name='Aviation warning light provided?')),
                ('has_other_antennas', models.BooleanField(default=False, verbose_name='Others Antennas on the Tower?')),
                ('other_antennas_details', models.TextField(blank=True, verbose_name='If yes, elaborate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towers', to='broadcasters.generaldata')),
            ],
            options={
                'db_table': 'towers',
            },
        ),
    ]
